# Generated by Django 5.1.2 on 2024-10-24 06:48

import app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=20)),
                ('attendee_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('HARD', 'Hard'), ('MEDIUM', 'Medium'), ('EASY', 'Easy')], max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeModel',
            fields=[
                ('id', models.CharField(default=app.utils.getUniqueAttendeeID, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('mobile', models.CharField(blank=True, default='NULL', max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorModel',
            fields=[
                ('id', models.CharField(default=app.utils.getUniqueCreatorID, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('mobile', models.CharField(blank=True, default='NULL', max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('question', models.CharField(max_length=150)),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('selected', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('points', models.IntegerField()),
                ('quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.answermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=25)),
                ('B', models.CharField(max_length=25)),
                ('C', models.CharField(max_length=25)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.questionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.CharField(default=app.utils.getUniqueQuizID, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('HARD', 'Hard'), ('MEDIUM', 'Medium'), ('EASY', 'Easy')], max_length=6)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.creatormodel')),
            ],
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.quizmodel'),
        ),
    ]
