# Generated by Django 5.1.2 on 2024-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
