# Generated by Django 5.1.2 on 2024-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemodel',
            name='mobile',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='creatormodel',
            name='mobile',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
