# Generated by Django 5.1.2 on 2024-10-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attendeemodel_mobile_alter_creatormodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemodel',
            name='mobile',
            field=models.CharField(blank=True, default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='creatormodel',
            name='mobile',
            field=models.CharField(blank=True, default='NULL', max_length=10),
        ),
    ]
