# Generated by Django 5.1.2 on 2024-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(choices=[('Creator', '1'), ('Attendee', '2')], default='1', max_length=8),
        ),
    ]
