# Generated by Django 5.1.2 on 2024-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(choices=[('CREATOR', '1'), ('ATTENDEE', '2')], default='1', max_length=8),
        ),
    ]
